### ISSUE TITLE
PyQt5 Material Theme example renders black box

### ISSUE THREAD

**Issue by prurph** [eyllanesc/stackoverflow#12]
I checked out [this example](https://github.com/eyllanesc/stackoverflow/tree/586e25c95bc5014874c58389c12947bf77037afc/PyQt%20Material%20Qml) and tried running it using PyQt5 5.8 but I just see a black box. Any idea what might be going wrong? I didn't change the code at all.

![image](https://user-images.githubusercontent.com/6109531/52746741-3a471f80-2fb0-11e9-8fd5-55ad2a2e15b1.png)

**Comment by eyllanesc** [comment]
I have added other ways to enable the material design style based on [my other answer](https://stackoverflow.com/a/48583334/6622587), I recommend you try main2.py or main3.py since you do not use the qrc. Maybe the xxx_rc.py is not compatible with Mac OS and compiles it in Linux so another possible solution is that you compile the .qrc using pyrcc. The code is in: https://github.com/eyllanesc/stackoverflow/tree/master/others/PyQt%20Material%20Qml

**Comment by prurph** [comment]
Thanks for the quick response! I actually had found that answer and tried the other methods before posting and neither worked.

I was, however, able to get everything working (including the .qrc) by uninstalling PyQt5 and installing the latest version. Perhaps my installation was corrupted/broken, or maybe there was a bug on OS X that was fixed in later versions. Thanks!
